import {
  LayoutDashboard,
  ScanLine,
  CreditCard,
  Wallet,
  BarChart3,
  Sparkles,
  Target,
  Repeat,
  Receipt,
  FileText,
  Landmark,
  Users,
  FileBarChart,
  Flag,
  ShieldCheck,
  Brain,
  TrendingUp,
  type LucideIcon,
} from "lucide-react";

export type NavItem = { label: string; href: string; icon: LucideIcon; also?: string[]; exclude?: string[] };

export const NAV: NavItem[] = [
  { label: "Dashboard", href: "/", icon: LayoutDashboard, also: ["/overview", "/financial-health"] },
  { label: "Scan", href: "/scanner", icon: ScanLine },
  { label: "Expenses", href: "/expenses", icon: CreditCard },
  { label: "Income", href: "/income", icon: Wallet },
  { label: "Analytics", href: "/analytics", icon: BarChart3 },
  { label: "AI", href: "/ai", icon: Sparkles, exclude: ["/ai/anomalies"] },
  { label: "Security", href: "/ai/anomalies", icon: ShieldCheck },
  { label: "Budgets", href: "/budgets", icon: Target },
  { label: "Subscriptions", href: "/subscriptions", icon: Repeat },
  { label: "Bills", href: "/bills", icon: Receipt },
  { label: "Invoices", href: "/invoices", icon: FileText },
  { label: "Accounts", href: "/accounts", icon: Landmark },
  { label: "Shared", href: "/shared", icon: Users },
  { label: "Reports", href: "/reports", icon: FileBarChart },
  { label: "Goals", href: "/goals", icon: Flag },
  { label: "Investments", href: "/investments", icon: TrendingUp },
  { label: "RAG", href: "/rag", icon: Brain },
];

export function isActive(item: NavItem, pathname: string) {
  if (item.exclude?.some((e) => pathname.startsWith(e))) return false;
  if (item.href === "/") return pathname === "/" || !!item.also?.some((a) => pathname.startsWith(a));
  return pathname.startsWith(item.href);
}

export type PageEntry = { label: string; href: string; group: string; keywords?: string };

export const PAGES: PageEntry[] = [
  { label: "Dashboard", href: "/", group: "Dashboard", keywords: "home overview" },
  { label: "Overview", href: "/overview", group: "Dashboard", keywords: "360 summary" },
  { label: "Financial Health", href: "/financial-health", group: "Dashboard", keywords: "score" },
  { label: "Expenses", href: "/expenses", group: "Expenses", keywords: "transactions spending" },
  { label: "Add Expense", href: "/expenses/new", group: "Expenses", keywords: "new create" },
  { label: "Recurring Expenses", href: "/expenses/recurring", group: "Expenses", keywords: "repeat" },
  { label: "Expense Categories", href: "/expenses/categories", group: "Expenses" },
  { label: "Receipt Scanner", href: "/scanner", group: "Scanner", keywords: "ocr upload camera" },
  { label: "Batch Scanner", href: "/scanner/batch", group: "Scanner", keywords: "multiple" },
  { label: "OCR History", href: "/scanner/history", group: "Scanner", keywords: "scans" },
  { label: "Income", href: "/income", group: "Income", keywords: "salary earnings" },
  { label: "Add Income", href: "/income/new", group: "Income" },
  { label: "Analytics", href: "/analytics", group: "Analytics", keywords: "charts" },
  { label: "Spending Analytics", href: "/analytics/spending", group: "Analytics", keywords: "daily weekly heatmap velocity" },
  { label: "Category Analytics", href: "/analytics/categories", group: "Analytics" },
  { label: "Merchant Analytics", href: "/analytics/merchants", group: "Analytics" },
  { label: "Cash Flow", href: "/analytics/cash-flow", group: "Analytics", keywords: "inflow outflow" },
  { label: "AI Assistant", href: "/ai", group: "AI", keywords: "chat ask" },
  { label: "AI Insights", href: "/ai/insights", group: "AI" },
  { label: "Predictions", href: "/ai/predictions", group: "AI", keywords: "forecast" },
  { label: "Security Center", href: "/ai/anomalies", group: "AI", keywords: "fraud anomaly risk" },
  { label: "Financial Advisor", href: "/ai/advisor", group: "AI", keywords: "advice" },
  { label: "Budgets", href: "/budgets", group: "Budgets" },
  { label: "Create Budget", href: "/budgets/new", group: "Budgets" },
  { label: "Budget Calendar", href: "/budgets/calendar", group: "Budgets" },
  { label: "Subscriptions", href: "/subscriptions", group: "Subscriptions", keywords: "netflix recurring" },
  { label: "Renewal Calendar", href: "/subscriptions/calendar", group: "Subscriptions" },
  { label: "Bills", href: "/bills", group: "Bills", keywords: "due" },
  { label: "Bill Calendar", href: "/bills/calendar", group: "Bills" },
  { label: "Invoices", href: "/invoices", group: "Invoices" },
  { label: "Invoice Scanner", href: "/invoices/scanner", group: "Invoices" },
  { label: "Accounts", href: "/accounts", group: "Accounts", keywords: "bank" },
  { label: "Cards", href: "/accounts/cards", group: "Accounts", keywords: "credit debit" },
  { label: "Wallets", href: "/accounts/wallets", group: "Accounts" },
  { label: "Shared Expenses", href: "/shared", group: "Shared", keywords: "split" },
  { label: "Groups", href: "/shared/groups", group: "Shared" },
  { label: "Settlements", href: "/shared/settlements", group: "Shared", keywords: "settle up" },
  { label: "Reports", href: "/reports", group: "Reports" },
  { label: "Generate Report", href: "/reports/generate", group: "Reports", keywords: "export pdf csv excel" },
  { label: "Financial Goals", href: "/goals", group: "Goals", keywords: "savings" },
  { label: "Create Goal", href: "/goals/new", group: "Goals" },
  { label: "Investments", href: "/investments", group: "Investments", keywords: "stocks crypto mutual funds portfolio" },
  { label: "Notifications", href: "/notifications", group: "General", keywords: "alerts" },
  { label: "Global Search", href: "/search", group: "General" },
  // RAG
  { label: "RAG Dashboard", href: "/rag", group: "RAG", keywords: "knowledge base vector hybrid" },
  { label: "RAG Documents", href: "/rag/documents", group: "RAG", keywords: "upload pdf receipt invoice" },
  { label: "Semantic Search", href: "/rag/search", group: "RAG", keywords: "vector similarity natural language" },
  { label: "Retrieval Debugger", href: "/rag/retrieval", group: "RAG", keywords: "debug chunks score pipeline" },
  { label: "RAG Chat", href: "/ai/rag", group: "RAG", keywords: "hybrid rag agent citations sources" },
  { label: "Profile", href: "/settings/profile", group: "Settings" },
  { label: "Settings", href: "/settings", group: "Settings", keywords: "currency language privacy" },
  { label: "Security Settings", href: "/settings/security", group: "Settings", keywords: "password 2fa" },
  { label: "Connected Apps", href: "/settings/connected-apps", group: "Settings", keywords: "integrations" },
  { label: "Notification Settings", href: "/settings/notifications", group: "Settings" },
  { label: "Appearance", href: "/settings/appearance", group: "Settings", keywords: "theme dark accent" },
  { label: "Data Management", href: "/settings/data", group: "Settings", keywords: "backup restore export delete activity log" },
];

export const SEGMENT_LABELS: Record<string, string> = {
  scanner: "Scanner",
  result: "Scan Result",
  batch: "Batch Scanner",
  history: "OCR History",
  expenses: "Expenses",
  new: "New",
  recurring: "Recurring",
  categories: "Categories",
  income: "Income",
  analytics: "Analytics",
  spending: "Spending",
  merchants: "Merchants",
  "cash-flow": "Cash Flow",
  ai: "AI",
  insights: "Insights",
  predictions: "Predictions",
  anomalies: "Security Center",
  advisor: "Advisor",
  budgets: "Budgets",
  calendar: "Calendar",
  subscriptions: "Subscriptions",
  bills: "Bills",
  invoices: "Invoices",
  scanner_: "Scanner",
  accounts: "Accounts",
  cards: "Cards",
  wallets: "Wallets",
  shared: "Shared",
  groups: "Groups",
  settlements: "Settlements",
  reports: "Reports",
  generate: "Generate",
  goals: "Goals",
  investments: "Investments",
  notifications: "Notifications",
  search: "Search",
  settings: "Settings",
  profile: "Profile",
  security: "Security",
  "connected-apps": "Connected Apps",
  appearance: "Appearance",
  data: "Data Management",
  rag: "RAG",
  documents: "Documents",
  retrieval: "Retrieval Debugger",
  "financial-health": "Financial Health",
};

export const SHORTCUTS: { keys: string; action: string }[] = [
  { keys: "Ctrl / ⌘ + K", action: "Open command palette" },
  { keys: "/", action: "Search" },
  { keys: "?", action: "Show keyboard shortcuts" },
  { keys: "N", action: "New expense" },
  { keys: "S", action: "Scan a receipt" },
  { keys: "T", action: "Toggle dark / light mode" },
  { keys: "G then D", action: "Go to Dashboard" },
  { keys: "G then E", action: "Go to Expenses" },
  { keys: "G then A", action: "Go to Analytics" },
  { keys: "G then B", action: "Go to Budgets" },
  { keys: "G then I", action: "Go to AI Assistant" },
  { keys: "G then R", action: "Go to Reports" },
  { keys: "G then S", action: "Go to Settings" },
  { keys: "Esc", action: "Close dialogs & menus" },
];
